# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatabaseGenerica.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtWidgets import QMainWindow, QWidget, QLabel, QLineEdit
from PyQt5.QtWidgets import QPushButton

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 581)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 217, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)

        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)

        
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(0, 0, 971, 581))
        palette = QtGui.QPalette()
       
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 59, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)

        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 118, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)

        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 118, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)

        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 59, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        
        self.frame.setPalette(palette)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(12)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")

        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(30, 40, 20, 501))
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(900, 50, 20, 481))
        self.line_2.setLineWidth(0)
        self.line_2.setMidLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(40, 30, 881, 20))
        self.line_3.setLineWidth(0)
        self.line_3.setMidLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(40, 530, 880, 20))
        self.line_4.setLineWidth(0)
        self.line_4.setMidLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(40, 50, 20, 481))
        self.line_5.setLineWidth(0)
        self.line_5.setMidLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(910, 40, 20, 501))
        self.line_6.setLineWidth(0)
        self.line_6.setMidLineWidth(3)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setGeometry(QtCore.QRect(50, 40, 861, 20))
        self.line_7.setLineWidth(0)
        self.line_7.setMidLineWidth(3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(50, 520, 861, 20))
        self.line_8.setLineWidth(0)
        self.line_8.setMidLineWidth(3)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")

        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(80, 200, 811, 311))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        self.tableWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("background-color: rgb(249, 238, 214);\n""\n""")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)

        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(249, 238, 214))
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(249, 238, 214))
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(249, 238, 214))
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(249, 238, 214))
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(249, 238, 214))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(249, 238, 214))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(249, 238, 214))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(249, 238, 214))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 3, item)



        self.line = QtWidgets.QLineEdit(self.frame)
        self.line.setGeometry(QtCore.QRect(80, 80, 351, 31))

        button = pybutton = QPushButton('Pesquisar', self)
        button.setGeometry(QtCore.QRect(450, 80, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(175, 64, 68))
        button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setWeight(50)
        button.setFont(font)
        button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "color: rgb(175, 64, 68);\n")
        button.setObjectName("pushButton")   
        button.clicked.connect(self.clickMethod)



        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def clickMethod(self):
        print('Your name: ' + self.line.text())

    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Linha 01"))
        item = self.tableWidget.verticalHeaderItem(1)

        item.setText(_translate("MainWindow", "Linha 02"))
        item = self.tableWidget.verticalHeaderItem(2)

        item.setText(_translate("MainWindow", "Linha 03"))
        item = self.tableWidget.verticalHeaderItem(3)

        item.setText(_translate("MainWindow", "Linha 04"))
        item = self.tableWidget.horizontalHeaderItem(0)

        item.setText(_translate("MainWindow", "Coluna 01"))
        item = self.tableWidget.horizontalHeaderItem(1)

        item.setText(_translate("MainWindow", "Coluna 02"))
        item = self.tableWidget.horizontalHeaderItem(2)

        item.setText(_translate("MainWindow", "Coluna 03"))
        item = self.tableWidget.horizontalHeaderItem(3)

        item.setText(_translate("MainWindow", "Coluna 04"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)

        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "00"))
        item = self.tableWidget.item(0, 1)

        item.setText(_translate("MainWindow", "01"))
        item = self.tableWidget.item(0, 2)

        item.setText(_translate("MainWindow", "02"))
        item = self.tableWidget.item(0, 3)

        item.setText(_translate("MainWindow", "03"))
        item = self.tableWidget.item(1, 0)

        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.item(1, 1)

        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.item(1, 2)

        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.item(1, 3)

        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.item(2, 0)

        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget.item(2, 1)

        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget.item(2, 2)

        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget.item(2, 3)

        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget.item(3, 0)

        item.setText(_translate("MainWindow", "30"))
        item = self.tableWidget.item(3, 1)

        item.setText(_translate("MainWindow", "31"))
        item = self.tableWidget.item(3, 2)

        item.setText(_translate("MainWindow", "32"))
        item = self.tableWidget.item(3, 3)

        item.setText(_translate("MainWindow", "33"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)



class Search(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)

        self.line = QLineEdit(self)
        self.line.setGeometry(QtCore.QRect(80, 80, 351, 31))

        button = QPushButton('Pesquisar', self)
        button.setGeometry(QtCore.QRect(450, 80, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(175, 64, 68))
        button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setWeight(50)
        button.setFont(font)
        button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "color: rgb(175, 64, 68);\n")
        button.setObjectName("pushButton")   
        button.clicked.connect(self.clickMethod)

    def clickMethod(self):
        print('Your name: ' + self.line.text())

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
