insert into Monstro(codigoDeus,	nomeDeus, mitologia, dominio, tendencia, simbolo, descricao) values
('O Daghdha', 'Celta', 'Enganação, Natureza', 'CB', 'Caldeirão borbulhante ou escudo', 'deus do clima e das colheitas'),
('Arawn', 'Celta', 'Morte, Vid', 'NM', 'Estrela negra num fundo cinza', 'deus da vida e da morte'),
('Belenus', 'Celta', 'Luz', 'NB', 'Disco solar e monólitos', 'deus do sol, da luz e do calor'),
('Brigantia', 'Celta', 'Vida', 'NB', 'Passarela', 'deusa dos rios e da pecuária'),
('Diancecht', 'Celta', 'Vida', 'LB', 'Ramos de carvalho e visco cruzados', 'deus da medicina e da cura'),
('Dunatis', 'Celta', 'Natureza', 'N', 'Sol vermelho encoberto pelo pico da montanha', 'deus das montanhas e dos picos'),
('Goibhniu', 'Celta', 'Conhecimento, Vida', 'NB', 'Marreta gigante sobre espada', 'deus da ferraria e da cura'),
('Lugh', 'Celta', 'Conhecimento, Vida', 'CN', 'Par de mão longas', 'deus das artes, da viagem e do comércio'),
('Manannan mac Lir', 'Celta', 'Natureza, Tempestade', 'LN', 'Onda de água branca no gramado', 'deus dos oceanos e das criaturas marinhas'),
('Math Mathonwy', 'Celta', 'Conhecimento', 'NM', 'Cajado', 'deus da magia'),
('Morrigan', 'Celta', 'Guerra', 'CM', 'Duas lanças cruzadas', 'deusa da batalha'),
('Nuada', 'Celta', 'Guerra', 'N', 'Mão prateada num fundo preto', 'deus da guerra e dos guerreiros'),
('Oghma', 'Celta', 'Conhecimento', 'NB', 'Pergaminho desfraldado', 'deus da fala e da escrita'),
('Silvanus', 'Celta', 'Natureza', 'N', 'Carvalho no verão', 'deus da natureza e das florestas'),
('Zeus', 'Grega','Tempestade','N','Punho cheio de relâmpagos','deus dos céus, senhor dos deuses'),
('Afrodite', 'Grega','Luz','CB','Concha do mar','deusa do amor e da beleza'),
('Apolo', 'Grega','Conhecimento, Luz, Vida','CB','Lira','deus da luz, música e da cura'),
('Ares', 'Grega','Guerra','CM','Lança','deus da guerra e do conflito'),
('Artêmis', 'Grega','Natureza, Vida','NB','Arco e flecha num disco lunar','deusa da caça e do nascimento'),
('Atena', 'Grega','Conhecimento, Guerra','LB','Coruja','deusa da sabedoria e da civilização'),
('Demeter', 'Grega','Vida','BN','Cabeça de égua','deusa da agricultura'),
('Dionísio', 'Grega','Vida','CN','Thyrsus (cajado com ponta cônica de pinho)','deus da alegria e do vinho'),
('Hades', 'Grega','Morte','LM','Carneiro negro','deus do submundo'),
('Hecate', 'Grega','Conhecimento, Enganação','CM','Ocaso lunar','deusa da magia e da lua'),
('Hefesto', 'Grega','Conhecimento','NB','Martelo e bigorna','deus da forja e da construção'),
('Hera', 'Grega','Enganação','CN','Leque de penas de pavão','deusa do casamento e da intriga'),
('Hércules', 'Grega','Guerra, Tempestade','CB','Cabeça de leão','deus da força e da aventura'),
('Hermes', 'Grega','Enganação','CB','Caduceus (cajado alado e serpentes)','deus da viagem e do comércio'),
('Hestia', 'Grega','Vida','NB','Lareira','deusa do lar e da família'),
('Nike', 'Grega','Guerra','LN','Mulher alada','deusa da vitória'),
('Pã', 'Grega','Natureza','CN','Syrinx (flauta de pã)','deus da natureza'),
('Poseidon', 'Grega','Tempestade','CN','Tridente','deus do mar e dos terremotos'),
('Tyche', 'Grega','Enganação','N','Pentagrama vermelho','deusa da boa sorte'),
('Re-Horakhty', 'Egípcia', 'Luz, Vida', 'LB', 'Disco solar envolto por uma serpente', 'deus do sol, senhor dos deuses'),
('Anúbis', 'Egípcia', 'Morte', 'LN', 'Chacal negro', 'deus do julgamento e da morte'),
('Apep', 'Egípcia', 'Enganação', 'NM', 'Serpente flamejante', 'deus do mal, fogo e das serpentes'),
('Bast', 'Egípcia', 'Guerra', 'CB', 'Gato', 'deusa dos gatos e da vingança'),
('Bes', 'Egípcia', 'Enganação', 'CN', 'Imagem do deus deformado', 'deus da sorte e da música'),
('Hathor', 'Egípcia', 'Luz, Vida', 'NB', 'Cabeça de vaca com chifre e disco lunar', 'deusa do amor, da música e da maternidade'),
('Imhotep', 'Egípcia', 'Conhecimento', 'NB', 'Pirâmide de degraus', 'deus dos ofícios e da medicina'),
('Isis', 'Egípcia', 'Conhecimento, Vida, Vida', 'NB', 'Ankh e estrela', 'deusa da fertilidade e da magia'),
('Nephthys', 'Egípcia', 'Morte', 'CN', 'Chifres em volta de um disco lunar', 'deusa da morte e da tristeza'),
('Osíris', 'Egípcia', 'Natureza, Vida', 'LB', 'Gancho e mangual', 'deus da natureza e do submundo'),
('Ptah', 'Egípcia', 'Conhecimento', 'LN', 'Touro', 'deus dos ofícios, do conhecimento e dos segredos'),
('Set', 'Egípcia', 'Enganação, Morte, Tempestade', 'CM', 'Cobra enrolada', 'deus das trevas e das tempestades desérticas'),
('Sobek', 'Egípcia', 'Natureza, Tempestade', 'LM', 'Cabeça de crocodilo com chifres e plumas', 'deus da água e dos crocodilos'),
('Thoth', 'Egípcia', 'Conhecimento', 'N', 'Íbis', 'deus do conhecimento e da sabedoria'),
('Odin', 'Nórdica', 'Conhecimento, Guerra', 'NB', 'Olho azul vigilante', 'deus do conhecimento e da guerra'),
('Aegir', 'Nórdica', 'Tempestade', 'NM', 'Ondas oceânicas vigorosas', 'deus do mar e das tormentas'),
('Balder', 'Nórdica', 'Luz, Vida', 'NB', 'Cálice de prata incrustado com gemas', 'deus da beleza e da poesia'),
('Forseti', 'Nórdica', 'Luz', 'N', 'Cabeça de um homem barbudo', 'deus da justiça e da lei'),
('Frey', 'Nórdica', 'Luz, Vida', 'NB', 'Espada grande azul-gelo', 'deus da fertilidade e do sol'),
('Freya', 'Nórdica', 'Vida', 'NB', 'Falcão', 'deusa da fertilidade e do amor'),
('Frigga', 'Nórdica', 'Luz, Vida', 'N', 'Gato', 'deusa do nascimento e da fertilidade'),
('Heimdall', 'Nórdica', 'Guerra, Luz', 'LB', 'Trombeta', 'deus da vigilância e da lealdade'),
('Hel', 'Nórdica', 'Morte', 'NM', 'Rosto de mulher, apodrecido de um lado', 'deusa do submundo'),
('Hermod', 'Nórdica', 'Enganação', 'CN', 'Pergaminho alado', 'deus da sorte'),
('Loki', 'Nórdica', 'Enganação', 'CM', 'Chamas', 'deus dos ladrões e da trapaça'),
('Njord', 'Nórdica', 'Natureza, Tempestade', 'NB', 'Moeda de ouro', 'deus do mar e do vento'),
('Odur', 'Nórdica', 'Luz', 'CB', 'Disco solar', 'deus da luz e do sol'),
('Sif', 'Nórdica', 'Guerra', 'CB', 'Espada erguida', 'deusa da guerra'),
('Sakadi', 'Nórdica', 'Natureza', 'N', 'Pico de montanha', 'deus da terra e das montanhas'),
('Surtur', 'Nórdica', 'Guerra', 'LM', 'Espada flamejante', 'deus dos gigantes do fogo e da guerra'),
('Thor', 'Nórdica', 'Guerra, Tempestade', 'CB', 'Martelo', 'deus das tempestades e do trovão'),
('Thrym', 'Nórdica', 'Guerra', 'CM', 'Machado branco de duas lâminas', 'deus dos gigantes do gelo e do frio'),
('Tyr', 'Nórdica', 'Conhecimento, Guerra', 'LN', 'Espada', 'deus da coragem e da estratégia'),
('Uller', 'Nórdica', 'Natureza', 'CN', 'Arco longo', 'deus da caça e do inverno');
